packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  '@tanstack/react-query': ^5.59.13
  '@trpc/client': ^11.0.0-rc.477
  '@trpc/react-query': ^11.0.0-rc.477
  '@trpc/server': ^11.0.0-rc.477
  '@types/node': ^20.16.5
  eslint: ^9.9.0
  prettier: ^3.3.3
  tailwindcss: ^3.4.10
  nativewind: ^4.0.36
  typescript: ^5.5.4
  zod: ^3.23.8

catalogs:
  react18:
    next: ^14.2.11
    react: ^18.3.1
    react-dom: ^18.3.1
    react-native: ^0.75.3
    react-native-web: ^0.19.10
    '@types/react': ^18.3.3
    '@types/react-dom': ^18.3.0
